### ISSUE TITLE
add total DAI sent from a given sender to a given receiver

### ISSUE THREAD

**Issue by xmxanuel** [radicle-dev/radicle-streaming#29]
It should be on-chain available, how much DAI each receiver has collected in total.

**Comment by manuelpolzhofer** [comment]
For the influence ` totalReceivedAmount` and `amtPerSec` will be the most important variables. It would be good to have availabe on-chain.

Lets imagine a DAO wants to distribute funds in an on-chain voting etc.

**Comment by CodeSandwich** [comment]
So the influence could be gained not only by **sending** funds, but also by **receiving**? Isn't the receiver of funds for a project always the project itself and its owner?
